Predicted Values

In [ ]:
# Requirements
# %pip install pandas numpy matplotlib fredapi python-dotenv scipy scikit-learn joblib tdqm xgboost seaborn

In [2]:
from src import *

c:\Users\Josiah Lee\Documents\GitHub\dse4212_portfolio_optimisation\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2017-02-08 start test to 2018-02-07

2014-03-03 start CV to 2016-10-03

In [14]:
with open('src/processed_data.pkl', 'rb') as f:
    op, high, low, close, volume, returns, risk_free_rate = pickle.load(f)

train_returns = returns.iloc[:-252]
test_returns = returns.iloc[-252:]
test_risk_free_rate = risk_free_rate.iloc[-252:]
cv_returns = train_returns.iloc[-252:]
cv_returns

Name,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,...,XL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
2016-02-09,0.016247,0.017843,0.000353,-0.000211,0.011093,0.013423,-0.012356,-0.018579,-0.014652,0.003047,...,0.001151,-0.003383,-0.013396,-0.003678,-0.032569,0.013438,-0.014339,-0.001414,0.002410,-0.008245
2016-02-10,0.013480,0.025373,-0.020924,-0.007609,-0.014313,0.009980,0.005660,0.009492,0.022494,-0.007123,...,-0.030080,-0.007440,-0.009158,0.012901,0.013606,-0.007657,0.004353,0.010930,-0.001445,-0.013386
2016-02-11,-0.014611,-0.017118,-0.001155,-0.006065,-0.010296,-0.012342,-0.023658,-0.008314,-0.007842,-0.002454,...,-0.015838,0.008075,0.003146,-0.021359,-0.021629,-0.006057,-0.023031,-0.013327,-0.041344,0.000762
2016-02-12,0.024879,0.035800,0.016907,0.003090,0.007637,0.012459,0.021506,0.013502,0.022823,0.016247,...,0.040726,0.008430,0.017805,-0.032006,0.009164,0.022663,0.031682,0.001090,0.053326,0.026822
2016-02-16,0.023466,0.020673,0.036479,0.027804,0.017533,0.000000,0.022898,0.023069,0.028417,0.047792,...,0.002022,0.008984,0.002342,0.017568,0.028108,-0.001080,0.031860,0.019850,0.032344,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-01,0.005905,-0.004530,-0.022474,0.059194,-0.003607,0.015123,0.013318,-0.005813,-0.000176,0.016280,...,0.009536,-0.014015,-0.011389,0.003521,0.020001,-0.003250,-0.010123,0.001520,0.006379,0.006893
2017-02-02,-0.007335,-0.000908,0.010838,-0.001710,0.000000,-0.006340,0.009873,0.003791,-0.001766,-0.012418,...,0.026280,0.012984,0.006130,-0.006701,0.014045,-0.007147,0.012257,-0.007538,-0.016384,0.006846
2017-02-03,0.009768,0.004308,0.002522,0.004270,-0.003620,0.013873,0.000702,0.007452,0.017607,0.003847,...,-0.007475,0.001375,0.001078,0.010910,-0.002793,0.009179,0.008491,0.004411,0.036205,0.003942
2017-02-06,-0.002230,0.024582,-0.015355,0.009330,-0.000330,0.007810,-0.008215,-0.002711,-0.006184,0.000132,...,0.006961,0.000172,-0.002757,0.002098,-0.011252,-0.042939,0.001056,-0.007647,-0.007881,-0.002686
2017-02-07,0.007482,-0.002874,-0.006824,0.009472,-0.001485,0.003882,0.010783,0.015124,0.004359,0.010274,...,0.000514,-0.002407,-0.006503,0.002965,0.000000,0.000847,0.002862,0.007393,-0.003497,0.003758

Predicting the returns

In [ ]:
# predictor = MLReturnPredictor(model_type='ridge', alpha=.1)
# X_train, y_train = predictor.create_training_dataset(os.listdir('src/data')[:os.listdir('src/data').index('2017-02-08.pkl')-65],
#                                                       train_returns.iloc[:-65]) #65 for purge
# predictor.train(X_train, y_train)
# predicted = predictor.predict_all_test_returns(os.listdir('src/data')[os.listdir('src/data').index('2017-02-08.pkl'):])

This is during the test period then to do walk forward can use this code

In [ ]:
from itertools import product
import random
random.seed(4212)

with open('src/data_weekly_ret/return_5_targets.pkl', 'rb') as f:
    weekly_volatility_targets = pickle.load(f)

mask = (weekly_volatility_targets.index >= '2014-03-03') & (weekly_volatility_targets.index <= '2016-10-03')
testing_data = weekly_volatility_targets.loc[mask]
testing_dates = testing_data.index.strftime('%Y-%m-%d').map(lambda x: x+".pkl").values

results_df = {}

for method in ['RF']:
    model_params = []
    if method == 'Ridge':
        alphas = [1e-06, 1e-07, 1e-08, 1e-09, 1e-10] # 5 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'Lasso':
        alphas = [.0001, 1e-05, 1e-06, 1e-07, 1e-08] # 5 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'ENet':
        alphas = [1e-06, 1e-07, 1e-08]
        l1_ratios = [.3, .5, .7]
        model_params = [{'alpha': a, 'l1_ratio': r} for a, r in product(alphas, l1_ratios)] #9 models
    elif method == 'RF':
        n_estimators=[10, 100, 500]
        max_depth=[3, 5, 7]
        min_samples_leaf=[50, 100, 500]
        max_features=['sqrt']
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'min_samples_leaf': l, 'max_features': f, 'n_jobs': j}
                        for n, d, l, f, j in product(n_estimators, max_depth, min_samples_leaf, max_features, [n_jobs])] #24 models
    elif method == 'XGB':
        n_estimators=[10, 100, 200]
        max_depth=[3, 5, 7]
        learning_rate=[0.05, 0.1]
        min_child_weight=[100, 200]
        reg_lambda=[.1, 1, 5]
        subsample=[0.8]
        colsample_bytree=[0.8]
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'learning_rate': lr,
                         'min_child_weight': mcw, 'reg_lambda': rl,
                         'subsample': ss, 'colsample_bytree': cb,
                         'n_jobs': j}
                        for n, d, lr, mcw, rl, ss, cb, j in
                        product(n_estimators, max_depth, learning_rate,
                                min_child_weight, reg_lambda,
                                subsample, colsample_bytree, [n_jobs])]
    def model_cv(model_params) -> dict:
        preds = []

        for test_date in testing_dates:
            predictor = MLReturnPredictor(model_type=method, **model_params)
            v = os.listdir('src/data_weekly_ret')[:os.listdir('src/data_weekly_ret').index(test_date)-14]
            X_train, y_train = predictor.create_training_dataset(v, "weekly_ret", weekly_volatility_targets)
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            predictor.train(X_train, y_train)
            predicted = predictor.predict_all_test_returns([test_date], "weekly_ret", scaler)
            preds.append(predicted)

        predicted = pd.concat(preds)
        return predicted

    weights_list = Parallel(n_jobs=-1)(
        delayed(model_cv)(d) for d in tqdm(model_params)
    )

    for i in range(len(weights_list)):
        model_param = model_params[i]
        results = evaluate_predictions(weights_list[i], testing_data)
        results_df[(method, frozenset(model_param.items()))] = results
results_df = pd.DataFrame(results_df).T
results_df

100%|██████████| 27/27 [05:23<00:00, 11.99s/it]

In [102]:
results_df.sort_values(('information_coefficient'), ascending=False)

                                        directional_accuracy  \
ENet ((alpha, 1e-08), (l1_ratio, 0.3))              0.555147
     ((alpha, 1e-08), (l1_ratio, 0.5))              0.555147
     ((alpha, 1e-08), (l1_ratio, 0.7))              0.555147
     ((alpha, 1e-07), (l1_ratio, 0.3))              0.555131
     ((l1_ratio, 0.5), (alpha, 1e-07))              0.555131
     ((l1_ratio, 0.7), (alpha, 1e-07))              0.555163
     ((alpha, 1e-06), (l1_ratio, 0.3))              0.555147
     ((alpha, 1e-06), (l1_ratio, 0.5))                0.5551
     ((alpha, 1e-06), (l1_ratio, 0.7))              0.555225
     ((alpha, 1e-05), (l1_ratio, 0.3))              0.555304
     ((alpha, 1e-05), (l1_ratio, 0.5))              0.555241
     ((alpha, 1e-05), (l1_ratio, 0.7))              0.555225
     ((l1_ratio, 0.3), (alpha, 0.0001))             0.555601
     ((l1_ratio, 0.5), (alpha, 0.0001))             0.555523
     ((l1_ratio, 0.7), (alpha, 0.0001))             0.555163

                                        information_coefficient  \
ENet ((alpha, 1e-08), (l1_ratio, 0.3))                 0.133031
     ((alpha, 1e-08), (l1_ratio, 0.5))                  0.13303
     ((alpha, 1e-08), (l1_ratio, 0.7))                  0.13303
     ((alpha, 1e-07), (l1_ratio, 0.3))                 0.133027
     ((l1_ratio, 0.5), (alpha, 1e-07))                 0.133024
     ((l1_ratio, 0.7), (alpha, 1e-07))                 0.133021
     ((alpha, 1e-06), (l1_ratio, 0.3))                 0.132989
     ((alpha, 1e-06), (l1_ratio, 0.5))                  0.13296
     ((alpha, 1e-06), (l1_ratio, 0.7))                 0.132934
     ((alpha, 1e-05), (l1_ratio, 0.3))                 0.132643
     ((alpha, 1e-05), (l1_ratio, 0.5))                 0.132374
     ((alpha, 1e-05), (l1_ratio, 0.7))                 0.132073
     ((l1_ratio, 0.3), (alpha, 0.0001))                0.129556
     ((l1_ratio, 0.5), (alpha, 0.0001))                0.127523
     ((l1_ratio, 0.7), (alpha, 0.0001))                0.125198

                                        pearson_correlation  \
ENet ((alpha, 1e-08), (l1_ratio, 0.3))             0.096513
     ((alpha, 1e-08), (l1_ratio, 0.5))             0.096512
     ((alpha, 1e-08), (l1_ratio, 0.7))             0.096512
     ((alpha, 1e-07), (l1_ratio, 0.3))             0.096506
     ((l1_ratio, 0.5), (alpha, 1e-07))             0.096501
     ((l1_ratio, 0.7), (alpha, 1e-07))             0.096496
     ((alpha, 1e-06), (l1_ratio, 0.3))              0.09644
     ((alpha, 1e-06), (l1_ratio, 0.5))             0.096392
     ((alpha, 1e-06), (l1_ratio, 0.7))             0.096344
     ((alpha, 1e-05), (l1_ratio, 0.3))             0.095805
     ((alpha, 1e-05), (l1_ratio, 0.5))             0.095331
     ((alpha, 1e-05), (l1_ratio, 0.7))             0.094846
     ((l1_ratio, 0.3), (alpha, 0.0001))            0.090646
     ((l1_ratio, 0.5), (alpha, 0.0001))            0.087958
     ((l1_ratio, 0.7), (alpha, 0.0001))            0.085689

                                                       confusion_matrix  \
ENet ((alpha, 1e-08), (l1_ratio, 0.3))   [[7579, 21532], [6855, 27954]]
     ((alpha, 1e-08), (l1_ratio, 0.5))   [[7579, 21532], [6855, 27954]]
     ((alpha, 1e-08), (l1_ratio, 0.7))   [[7579, 21532], [6855, 27954]]
     ((alpha, 1e-07), (l1_ratio, 0.3))   [[7578, 21533], [6855, 27954]]
     ((l1_ratio, 0.5), (alpha, 1e-07))   [[7578, 21533], [6855, 27954]]
     ((l1_ratio, 0.7), (alpha, 1e-07))   [[7580, 21531], [6855, 27954]]
     ((alpha, 1e-06), (l1_ratio, 0.3))   [[7578, 21533], [6854, 27955]]
     ((alpha, 1e-06), (l1_ratio, 0.5))   [[7578, 21533], [6857, 27952]]
     ((alpha, 1e-06), (l1_ratio, 0.7))   [[7579, 21532], [6850, 27959]]
     ((alpha, 1e-05), (l1_ratio, 0.3))   [[7567, 21544], [6833, 27976]]
     ((alpha, 1e-05), (l1_ratio, 0.5))   [[7570, 21541], [6840, 27969]]
     ((alpha, 1e-05), (l1_ratio, 0.7))   [[7549, 21562], [6820, 27989]]
     ((l1_ratio, 0.3), (alpha, 0.0001))  [[7432, 21679], [6681, 28128]]
     ((l1_ratio, 0.5), (alpha, 0.0001))  [[7329, 21782], [6586, 28223]]
     ((l1_ratio, 0.7), (alpha, 0.0001))  [[7197, 21914], [6477, 28332]]

                                        precision    recall  r2_score
ENet ((alpha, 1e-08), (l1_ratio, 0.3))   0.564887  0.803068 -0.015733
     ((alpha, 1e-08), (l1_ratio, 0.5))   0.564887  0.803068 -0.015733
     ((alpha, 1e-08), (l1_ratio, 0.7))   0.564887  0.803068 -0.015733
     ((alpha, 1e-07), (l1_ratio, 0.3))   0.564876  0.803068 -0.015732
     ((l1_ratio, 0.5), (alpha, 1e-07))   0.564876  0.803068 -0.015731
     ((l1_ratio, 0.7), (alpha, 1e-07))   0.564898  0.803068  -0.01573
     ((alpha, 1e-06), (l1_ratio, 0.3))   0.564884  0.803097  -0.01572
     ((alpha, 1e-06), (l1_ratio, 0.5))   0.564858  0.803011 -0.015712
     ((alpha, 1e-06), (l1_ratio, 0.7))   0.564931  0.803212 -0.015704
     ((alpha, 1e-05), (l1_ratio, 0.3))   0.564943    0.8037   -0.0156
     ((alpha, 1e-05), (l1_ratio, 0.5))   0.564916  0.803499 -0.015524
     ((alpha, 1e-05), (l1_ratio, 0.7))   0.564852  0.804074 -0.015455
     ((l1_ratio, 0.3), (alpha, 0.0001))   0.56474  0.808067 -0.014395
     ((l1_ratio, 0.5), (alpha, 0.0001))  0.564404  0.810796 -0.013731
     ((l1_ratio, 0.7), (alpha, 0.0001))  0.563866  0.813927 -0.012917

In [ ]:
from itertools import product
import random
random.seed(4212)

with open('src/data_daily_ret/return_1_targets.pkl', 'rb') as f:
    daily_volatility_targets = pickle.load(f)

mask = (daily_volatility_targets.index >= '2014-03-03') & (daily_volatility_targets.index <= '2016-10-03')
testing_data = daily_volatility_targets.loc[mask]
testing_dates = testing_data.index.strftime('%Y-%m-%d').map(lambda x: x+".pkl").values

results_df = {}

for method in ['Ridge', 'Lasso', 'ENet', 'RF']:
    model_params = []
    if method == 'Ridge':
        alphas = [1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9] # 7 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'Lasso':
        alphas = [.01, .001, .0001, 1e-05, 1e-06, 1e-07] # 6 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'ENet':
        alphas = [.01, .001, .0001, 1e-05, 1e-06, 1e-07]
        l1_ratios = [.3, .5, .7]
        model_params = [{'alpha': a, 'l1_ratio': r} for a, r in product(alphas, l1_ratios)] #20 models
    elif method == 'RF':
        n_estimators=[10, 100]
        max_depth=[3, 5, 7]
        min_samples_leaf=[50, 100, 500]
        max_features=['sqrt']
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'min_samples_leaf': l, 'max_features': f, 'n_jobs': j}
                        for n, d, l, f, j in product(n_estimators, max_depth, min_samples_leaf, max_features, [n_jobs])] #24 models
    elif method == 'XGB':
        n_estimators=[10, 100]
        max_depth=[3, 5, 7]
        learning_rate=[0.05, 0.1]
        min_child_weight=[100, 200]
        reg_lambda=[.1, 1, 5]
        subsample=[0.8]
        colsample_bytree=[0.8]
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'learning_rate': lr,
                         'min_child_weight': mcw, 'reg_lambda': rl,
                         'subsample': ss, 'colsample_bytree': cb,
                         'n_jobs': j}
                        for n, d, lr, mcw, rl, ss, cb, j in
                        product(n_estimators, max_depth, learning_rate,
                                min_child_weight, reg_lambda,
                                subsample, colsample_bytree, [n_jobs])]
    def model_cv(model_params) -> dict:
        preds = []

        for test_date in testing_dates:
            predictor = MLReturnPredictor(model_type=method, **model_params)
            v = os.listdir('src/data_daily_ret')[:os.listdir('src/data_daily_ret').index(test_date)-70]
            X_train, y_train = predictor.create_training_dataset(v, "daily_ret", daily_volatility_targets)
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            predictor.train(X_train, y_train*10000)  # Scale up targets for daily returns
            predicted = predictor.predict_all_test_returns([test_date], "daily_ret", scaler)/10000  # Scale down predictions
            preds.append(predicted)

        predicted = pd.concat(preds)
        return predicted

    weights_list = Parallel(n_jobs=-1)(
        delayed(model_cv)(d) for d in tqdm(model_params)
    )

    for i in range(len(weights_list)):
        model_param = model_params[i]
        results = evaluate_predictions(weights_list[i], testing_data)
        results_df[(method, frozenset(model_param.items()))] = results
results_df = pd.DataFrame(results_df).T
results_df

100%|██████████| 4/4 [00:00<00:00, 1337.90it/s]

============================================================
PREDICTION EVALUATION
============================================================
Total observations: 307,380
Dates: 654, Stocks: 470

1. DIRECTIONAL ACCURACY: 51.30%
   ~ Weak signal

2. INFORMATION COEFFICIENT: 0.0402 (p=0.0000)
   ~ Weak but non-zero

3. PEARSON CORRELATION: 0.0322

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [ 43815 105020]
        Up    [ 43830 114715]

   Precision (when predict Up): 52.21%
   Recall (catch actual Ups): 72.35%

5. R2 SCORE: -0.0092
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 307,380
Dates: 654, Stocks: 470

1. DIRECTIONAL ACCURACY: 51.30%
   ~ Weak signal

2. INFORMATION COEFFICIENT: 0.0402 (p=0.0000)
   ~ Weak but non-zero

3. PEARSON CORRELATION: 0.0322

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [ 43818 105017]
        Up    [ 43836 114709]

   Precision (when predict Up): 52.21%
   Recall (catch actual Ups): 72.35%

5. R2 SCORE: -0.0092
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 307,380
Dates: 654, Stocks: 470

1. DIRECTIONAL ACCURACY: 51.30%
   ~ Weak signal

2. INFORMATION COEFFICIENT: 0.0402 (p=0.0000)
   ~ Weak but non-zero

3. PEARSON CORRELATION: 0.0322

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [ 43818 105017]
        Up    [ 43837 114708]

   Precision (when predict Up): 52.21%
   Recall (catch actual Ups): 72.35%

5. R2 SCORE: -0.0092
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 307,380
Dates: 654, Stocks: 470

1. DIRECTIONAL ACCURACY: 51.30%
   ~ Weak signal

2. INFORMATION COEFFICIENT: 0.0402 (p=0.0000)
   ~ Weak but non-zero

3. PEARSON CORRELATION: 0.0322

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [ 43818 105017]
        Up    [ 43835 114710]

   Precision (when predict Up): 52.21%
   Recall (catch actual Ups): 72.35%

5. R2 SCORE: -0.0092

100%|██████████| 6/6 [00:00<00:00, 11057.04it/s]

KeyboardInterrupt:

In [10]:
with open('src/monthly_return_model_results.pkl', 'rb') as f:
    results_df = pickle.load(f)
results_df.sort_values(('information_coefficient'), ascending=False).head(10)

                                         directional_accuracy  \
ENet  ((l1_ratio, 0.1), (alpha, 0.001))              0.550066
Lasso ((alpha, 0.0001))                              0.549934
ENet  ((l1_ratio, 0.3), (alpha, 0.001))              0.551928
      ((l1_ratio, 0.9), (alpha, 0.0001))             0.549335
      ((l1_ratio, 0.7), (alpha, 0.0001))             0.549335
      ((l1_ratio, 0.5), (alpha, 0.0001))             0.550066
      ((alpha, 0.0001), (l1_ratio, 0.3))             0.549867
      ((l1_ratio, 0.1), (alpha, 0.0001))             0.549402
Lasso ((alpha, 1e-05))                               0.549468
      ((alpha, 1e-06))                                0.54867

                                         information_coefficient  \
ENet  ((l1_ratio, 0.1), (alpha, 0.001))                 0.145822
Lasso ((alpha, 0.0001))                                 0.145542
ENet  ((l1_ratio, 0.3), (alpha, 0.001))                 0.144997
      ((l1_ratio, 0.9), (alpha, 0.0001))                0.144871
      ((l1_ratio, 0.7), (alpha, 0.0001))                0.143732
      ((l1_ratio, 0.5), (alpha, 0.0001))                0.142773
      ((alpha, 0.0001), (l1_ratio, 0.3))                0.141839
      ((l1_ratio, 0.1), (alpha, 0.0001))                0.140838
Lasso ((alpha, 1e-05))                                  0.140784
      ((alpha, 1e-06))                                  0.140208

                                         pearson_correlation  \
ENet  ((l1_ratio, 0.1), (alpha, 0.001))             0.097712
Lasso ((alpha, 0.0001))                             0.097239
ENet  ((l1_ratio, 0.3), (alpha, 0.001))             0.101511
      ((l1_ratio, 0.9), (alpha, 0.0001))            0.095989
      ((l1_ratio, 0.7), (alpha, 0.0001))            0.093609
      ((l1_ratio, 0.5), (alpha, 0.0001))             0.09151
      ((alpha, 0.0001), (l1_ratio, 0.3))            0.089668
      ((l1_ratio, 0.1), (alpha, 0.0001))            0.087857
Lasso ((alpha, 1e-05))                              0.087742
      ((alpha, 1e-06))                              0.086901

                                                      confusion_matrix  \
ENet  ((l1_ratio, 0.1), (alpha, 0.001))   [[1912, 4896], [1868, 6364]]
Lasso ((alpha, 0.0001))                   [[1930, 4878], [1888, 6344]]
ENet  ((l1_ratio, 0.3), (alpha, 0.001))   [[1776, 5032], [1704, 6528]]
      ((l1_ratio, 0.9), (alpha, 0.0001))  [[1943, 4865], [1910, 6322]]
      ((l1_ratio, 0.7), (alpha, 0.0001))  [[1974, 4834], [1940, 6292]]
      ((l1_ratio, 0.5), (alpha, 0.0001))  [[2011, 4797], [1966, 6266]]
      ((alpha, 0.0001), (l1_ratio, 0.3))  [[2048, 4760], [2006, 6226]]
      ((l1_ratio, 0.1), (alpha, 0.0001))  [[2078, 4730], [2043, 6189]]
Lasso ((alpha, 1e-05))                    [[2081, 4727], [2045, 6187]]
      ((alpha, 1e-06))                    [[2092, 4716], [2068, 6164]]

                                         precision    recall  r2_score
ENet  ((l1_ratio, 0.1), (alpha, 0.001))   0.565187  0.773081 -0.099366
Lasso ((alpha, 0.0001))                   0.565318  0.770651 -0.103517
ENet  ((l1_ratio, 0.3), (alpha, 0.001))   0.564706  0.793003  -0.07804
      ((l1_ratio, 0.9), (alpha, 0.0001))   0.56512  0.767979 -0.106244
      ((l1_ratio, 0.7), (alpha, 0.0001))  0.565522  0.764334 -0.111949
      ((l1_ratio, 0.5), (alpha, 0.0001))  0.566392  0.761176 -0.117763
      ((alpha, 0.0001), (l1_ratio, 0.3))  0.566721  0.756317 -0.123724
      ((l1_ratio, 0.1), (alpha, 0.0001))   0.56681  0.751822 -0.129992
Lasso ((alpha, 1e-05))                    0.566887  0.751579 -0.130892
      ((alpha, 1e-06))                    0.566544  0.748785 -0.133993

In [ ]:
from itertools import product
import random
random.seed(4212)

with open('src/data_monthly_ret/return_21_targets.pkl', 'rb') as f:
    monthly_volatility_targets = pickle.load(f)

mask = (monthly_volatility_targets.index >= '2014-03-03') & (monthly_volatility_targets.index <= '2016-10-03')
testing_data = monthly_volatility_targets.loc[mask]
testing_dates = testing_data.index.strftime('%Y-%m-%d').map(lambda x: x+".pkl").values

results_df = {}

for method in ['Ridge', 'Lasso', 'ENet', 'RF', 'XGB']:
    model_params = []
    if method == 'Ridge':
        alphas = [1e-05, 1e-06, 1e-07, 1e-08, 1e-09, 1e-10] # 6 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'Lasso':
        alphas = [.01, .001, .0001, 1e-05, 1e-06, 1e-07] # 6 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'ENet':
        alphas = [.01, .001, .0001]
        l1_ratios = [.1, .3, .5, .7, .9]
        model_params = [{'alpha': a, 'l1_ratio': r} for a, r in product(alphas, l1_ratios)] #20 models
    elif method == 'RF':
        n_estimators=[10, 100, 500]
        max_depth=[3, 5, 7]
        min_samples_leaf=[50, 100, 500]
        max_features=['sqrt']
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'min_samples_leaf': l, 'max_features': f, 'n_jobs': j}
                        for n, d, l, f, j in product(n_estimators, max_depth, min_samples_leaf, max_features, [n_jobs])] #24 models
    elif method == 'XGB':
        n_estimators=[10, 100, 200]
        max_depth=[3, 5, 7]
        learning_rate=[0.05, 0.1]
        min_child_weight=[100, 200]
        reg_lambda=[.1, 1, 5]
        subsample=[0.8]
        colsample_bytree=[0.8]
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'learning_rate': lr,
                         'min_child_weight': mcw, 'reg_lambda': rl,
                         'subsample': ss, 'colsample_bytree': cb,
                         'n_jobs': j}
                        for n, d, lr, mcw, rl, ss, cb, j in
                        product(n_estimators, max_depth, learning_rate,
                                min_child_weight, reg_lambda,
                                subsample, colsample_bytree, [n_jobs])]
    def model_cv(model_params) -> dict:
        preds = []

        for test_date in testing_dates:
            predictor = MLReturnPredictor(model_type=method, **model_params)
            v = os.listdir('src/data_monthly_ret')[:os.listdir('src/data_monthly_ret').index(test_date)-4]
            X_train, y_train = predictor.create_training_dataset(v, "monthly_ret", monthly_volatility_targets)
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            predictor.train(X_train, y_train)
            predicted = predictor.predict_all_test_returns([test_date], "monthly_ret", scaler)
            preds.append(predicted)

        predicted = pd.concat(preds)
        return predicted

    weights_list = Parallel(n_jobs=-1)(
        delayed(model_cv)(d) for d in tqdm(model_params)
    )

    for i in range(len(weights_list)):
        model_param = model_params[i]
        results = evaluate_predictions(weights_list[i], testing_data)
        results_df[(method, frozenset(model_param.items()))] = results
results_df = pd.DataFrame(results_df).T
results_df.to_pickle('src/cv_results/monthly_return_model_results.pkl')

100%|██████████| 6/6 [00:00<00:00, 9888.34it/s]

============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.86%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1401 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0868

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2093   4715]
        Up    [  2070   6162]

   Precision (when predict Up): 56.65%
   Recall (catch actual Ups): 74.85%

5. R2 SCORE: -0.1344
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.86%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1401 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0868

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2093   4715]
        Up    [  2070   6162]

   Precision (when predict Up): 56.65%
   Recall (catch actual Ups): 74.85%

5. R2 SCORE: -0.1344
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.87%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1401 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0868

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2094   4714]
        Up    [  2070   6162]

   Precision (when predict Up): 56.66%
   Recall (catch actual Ups): 74.85%

5. R2 SCORE: -0.1344
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.87%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1401 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0869

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2096   4712]
        Up    [  2072   6160]

   Precision (when predict Up): 56.66%
   Recall (catch actual Ups): 74.83%

5. R2 SCORE: -0.1343
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.87%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1401 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0872

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2096   4712]
        Up    [  2071   6161]

   Precision (when predict Up): 56.66%
   Recall (catch actual Ups): 74.84%

5. R2 SCORE: -0.1342
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.03%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1396 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0875

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2118   4690]
        Up    [  2070   6162]

   Precision (when predict Up): 56.78%
   Recall (catch actual Ups): 74.85%

5. R2 SCORE: -0.1350

100%|██████████| 6/6 [00:00<00:00, 9727.80it/s]

============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.72%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0619 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0610

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [     1   6807]
        Up    [     3   8229]

   Precision (when predict Up): 54.73%
   Recall (catch actual Ups): 99.96%

5. R2 SCORE: -0.0109
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.45%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1311 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0944

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1745   5063]
        Up    [  1635   6597]

   Precision (when predict Up): 56.58%
   Recall (catch actual Ups): 80.14%

5. R2 SCORE: -0.0393
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.99%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1455 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0972

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1930   4878]
        Up    [  1888   6344]

   Precision (when predict Up): 56.53%
   Recall (catch actual Ups): 77.07%

5. R2 SCORE: -0.1035
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.95%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1408 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0877

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2081   4727]
        Up    [  2045   6187]

   Precision (when predict Up): 56.69%
   Recall (catch actual Ups): 75.16%

5. R2 SCORE: -0.1309
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.87%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1402 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0869

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2092   4716]
        Up    [  2068   6164]

   Precision (when predict Up): 56.65%
   Recall (catch actual Ups): 74.88%

5. R2 SCORE: -0.1340
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.87%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1401 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0868

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2093   4715]
        Up    [  2069   6163]

   Precision (when predict Up): 56.66%
   Recall (catch actual Ups): 74.87%

5. R2 SCORE: -0.1343

100%|██████████| 15/15 [00:00<00:00, 25679.41it/s]

============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.45%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1316 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0950

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1739   5069]
        Up    [  1628   6604]

   Precision (when predict Up): 56.58%
   Recall (catch actual Ups): 80.22%

5. R2 SCORE: -0.0355
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.69%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1320 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.1070

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1023   5785]
        Up    [   878   7354]

   Precision (when predict Up): 55.97%
   Recall (catch actual Ups): 89.33%

5. R2 SCORE: -0.0081
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.11%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1024 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0878

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   272   6536]
        Up    [   215   8017]

   Precision (when predict Up): 55.09%
   Recall (catch actual Ups): 97.39%

5. R2 SCORE: -0.0078
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.82%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0818 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0743

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [    70   6738]
        Up    [    57   8175]

   Precision (when predict Up): 54.82%
   Recall (catch actual Ups): 99.31%

5. R2 SCORE: -0.0097
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.75%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0641 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0665

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [     7   6801]
        Up    [     5   8227]

   Precision (when predict Up): 54.74%
   Recall (catch actual Ups): 99.94%

5. R2 SCORE: -0.0104
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.01%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1458 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0977

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1912   4896]
        Up    [  1868   6364]

   Precision (when predict Up): 56.52%
   Recall (catch actual Ups): 77.31%

5. R2 SCORE: -0.0994
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.19%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1450 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.1015

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1776   5032]
        Up    [  1704   6528]

   Precision (when predict Up): 56.47%
   Recall (catch actual Ups): 79.30%

5. R2 SCORE: -0.0780
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.24%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1390 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0970

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1754   5054]
        Up    [  1675   6557]

   Precision (when predict Up): 56.47%
   Recall (catch actual Ups): 79.65%

5. R2 SCORE: -0.0647
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.43%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1340 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0939

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1746   5062]
        Up    [  1638   6594]

   Precision (when predict Up): 56.57%
   Recall (catch actual Ups): 80.10%

5. R2 SCORE: -0.0540
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.55%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1322 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0946

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1752   5056]
        Up    [  1626   6606]

   Precision (when predict Up): 56.65%
   Recall (catch actual Ups): 80.25%

5. R2 SCORE: -0.0433
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.94%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1408 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0879

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2078   4730]
        Up    [  2043   6189]

   Precision (when predict Up): 56.68%
   Recall (catch actual Ups): 75.18%

5. R2 SCORE: -0.1300
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.99%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1418 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0897

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2048   4760]
        Up    [  2006   6226]

   Precision (when predict Up): 56.67%
   Recall (catch actual Ups): 75.63%

5. R2 SCORE: -0.1237
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.01%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1428 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0915

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  2011   4797]
        Up    [  1966   6266]

   Precision (when predict Up): 56.64%
   Recall (catch actual Ups): 76.12%

5. R2 SCORE: -0.1178
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.93%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1437 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0936

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1974   4834]
        Up    [  1940   6292]

   Precision (when predict Up): 56.55%
   Recall (catch actual Ups): 76.43%

5. R2 SCORE: -0.1119
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.93%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1449 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0960

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1943   4865]
        Up    [  1910   6322]

   Precision (when predict Up): 56.51%
   Recall (catch actual Ups): 76.80%

5. R2 SCORE: -0.1062

100%|██████████| 27/27 [00:00<00:00, 18702.92it/s]

============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.12%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0997 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0678

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1134   5674]
        Up    [  1225   7007]

   Precision (when predict Up): 55.26%
   Recall (catch actual Ups): 85.12%

5. R2 SCORE: -0.0271
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.09%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1101 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0770

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1052   5756]
        Up    [  1146   7086]

   Precision (when predict Up): 55.18%
   Recall (catch actual Ups): 86.08%

5. R2 SCORE: -0.0246
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.99%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1077 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0753

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   970   5838]
        Up    [   929   7303]

   Precision (when predict Up): 55.57%
   Recall (catch actual Ups): 88.71%

5. R2 SCORE: -0.0225
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.31%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1125 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0806

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1496   5312]
        Up    [  1558   6674]

   Precision (when predict Up): 55.68%
   Recall (catch actual Ups): 81.07%

5. R2 SCORE: -0.0359
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.57%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1119 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0805

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1471   5337]
        Up    [  1491   6741]

   Precision (when predict Up): 55.81%
   Recall (catch actual Ups): 81.89%

5. R2 SCORE: -0.0363
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.41%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1002 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0684

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1081   5727]
        Up    [   976   7256]

   Precision (when predict Up): 55.89%
   Recall (catch actual Ups): 88.14%

5. R2 SCORE: -0.0266
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.34%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1172 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0889

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1675   5133]
        Up    [  1728   6504]

   Precision (when predict Up): 55.89%
   Recall (catch actual Ups): 79.01%

5. R2 SCORE: -0.0442
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.21%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1189 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0811

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1665   5143]
        Up    [  1589   6643]

   Precision (when predict Up): 56.36%
   Recall (catch actual Ups): 80.70%

5. R2 SCORE: -0.0421
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.10%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1019 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0694

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1123   5685]
        Up    [  1066   7166]

   Precision (when predict Up): 55.76%
   Recall (catch actual Ups): 87.05%

5. R2 SCORE: -0.0270
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.77%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1076 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0792

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   981   5827]
        Up    [   973   7259]

   Precision (when predict Up): 55.47%
   Recall (catch actual Ups): 88.18%

5. R2 SCORE: -0.0215
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.80%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1081 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0793

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   992   5816]
        Up    [   979   7253]

   Precision (when predict Up): 55.50%
   Recall (catch actual Ups): 88.11%

5. R2 SCORE: -0.0214
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.05%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1077 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0761

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   807   6001]
        Up    [   756   7476]

   Precision (when predict Up): 55.47%
   Recall (catch actual Ups): 90.82%

5. R2 SCORE: -0.0207
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.89%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1132 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0840

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1437   5371]
        Up    [  1409   6823]

   Precision (when predict Up): 55.95%
   Recall (catch actual Ups): 82.88%

5. R2 SCORE: -0.0306
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.09%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1163 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0859

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1417   5391]
        Up    [  1358   6874]

   Precision (when predict Up): 56.05%
   Recall (catch actual Ups): 83.50%

5. R2 SCORE: -0.0295
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.20%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1048 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0738

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   963   5845]
        Up    [   890   7342]

   Precision (when predict Up): 55.68%
   Recall (catch actual Ups): 89.19%

5. R2 SCORE: -0.0234
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.79%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1144 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0825

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1656   5152]
        Up    [  1644   6588]

   Precision (when predict Up): 56.12%
   Recall (catch actual Ups): 80.03%

5. R2 SCORE: -0.0408
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.77%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1120 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0816

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1518   5290]
        Up    [  1508   6724]

   Precision (when predict Up): 55.97%
   Recall (catch actual Ups): 81.68%

5. R2 SCORE: -0.0363
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.90%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1036 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0723

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   912   5896]
        Up    [   884   7348]

   Precision (when predict Up): 55.48%
   Recall (catch actual Ups): 89.26%

5. R2 SCORE: -0.0241
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.65%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1050 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0777

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   989   5819]
        Up    [   999   7233]

   Precision (when predict Up): 55.42%
   Recall (catch actual Ups): 87.86%

5. R2 SCORE: -0.0211
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.66%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1048 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0781

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   974   5834]
        Up    [   982   7250]

   Precision (when predict Up): 55.41%
   Recall (catch actual Ups): 88.07%

5. R2 SCORE: -0.0210
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.96%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1080 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0768

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   784   6024]
        Up    [   747   7485]

   Precision (when predict Up): 55.41%
   Recall (catch actual Ups): 90.93%

5. R2 SCORE: -0.0200
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.81%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1142 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0868

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1443   5365]
        Up    [  1427   6805]

   Precision (when predict Up): 55.92%
   Recall (catch actual Ups): 82.67%

5. R2 SCORE: -0.0287
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.93%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1150 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0870

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1390   5418]
        Up    [  1356   6876]

   Precision (when predict Up): 55.93%
   Recall (catch actual Ups): 83.53%

5. R2 SCORE: -0.0279
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.11%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1060 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0738

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   953   5855]
        Up    [   894   7338]

   Precision (when predict Up): 55.62%
   Recall (catch actual Ups): 89.14%

5. R2 SCORE: -0.0229
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.77%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1146 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0849

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1626   5182]
        Up    [  1616   6616]

   Precision (when predict Up): 56.08%
   Recall (catch actual Ups): 80.37%

5. R2 SCORE: -0.0387
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.89%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1159 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0847

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1513   5295]
        Up    [  1486   6746]

   Precision (when predict Up): 56.03%
   Recall (catch actual Ups): 81.95%

5. R2 SCORE: -0.0348
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 55.09%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1073 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0751

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   961   5847]
        Up    [   905   7327]

   Precision (when predict Up): 55.62%
   Recall (catch actual Ups): 89.01%

5. R2 SCORE: -0.0230

100%|██████████| 108/108 [01:20<00:00,  1.34it/s]

============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.51%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0835 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0777

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [    76   6732]
        Up    [   109   8123]

   Precision (when predict Up): 54.68%
   Recall (catch actual Ups): 98.68%

5. R2 SCORE: -0.0117
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.56%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0832 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0776

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [    81   6727]
        Up    [   105   8127]

   Precision (when predict Up): 54.71%
   Recall (catch actual Ups): 98.72%

5. R2 SCORE: -0.0117
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.59%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0827 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0773

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [    79   6729]
        Up    [    99   8133]

   Precision (when predict Up): 54.72%
   Recall (catch actual Ups): 98.80%

5. R2 SCORE: -0.0116
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.57%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0861 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0798

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   102   6706]
        Up    [   124   8108]

   Precision (when predict Up): 54.73%
   Recall (catch actual Ups): 98.49%

5. R2 SCORE: -0.0112
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.58%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0861 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0798

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   103   6705]
        Up    [   124   8108]

   Precision (when predict Up): 54.74%
   Recall (catch actual Ups): 98.49%

5. R2 SCORE: -0.0112
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.64%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0865 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0802

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   102   6706]
        Up    [   114   8118]

   Precision (when predict Up): 54.76%
   Recall (catch actual Ups): 98.62%

5. R2 SCORE: -0.0110
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.46%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0976 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0830

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   537   6271]
        Up    [   727   7505]

   Precision (when predict Up): 54.48%
   Recall (catch actual Ups): 91.17%

5. R2 SCORE: -0.0185
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.33%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0964 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0821

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   531   6277]
        Up    [   740   7492]

   Precision (when predict Up): 54.41%
   Recall (catch actual Ups): 91.01%

5. R2 SCORE: -0.0187
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.26%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0950 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0802

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   526   6282]
        Up    [   746   7486]

   Precision (when predict Up): 54.37%
   Recall (catch actual Ups): 90.94%

5. R2 SCORE: -0.0192
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.52%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1005 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0851

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   485   6323]
        Up    [   665   7567]

   Precision (when predict Up): 54.48%
   Recall (catch actual Ups): 91.92%

5. R2 SCORE: -0.0175
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.50%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1000 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0849

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   487   6321]
        Up    [   671   7561]

   Precision (when predict Up): 54.47%
   Recall (catch actual Ups): 91.85%

5. R2 SCORE: -0.0175
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.58%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1021 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0860

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   513   6295]
        Up    [   684   7548]

   Precision (when predict Up): 54.53%
   Recall (catch actual Ups): 91.69%

5. R2 SCORE: -0.0170
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.78%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0891 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0806

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   258   6550]
        Up    [   400   7832]

   Precision (when predict Up): 54.46%
   Recall (catch actual Ups): 95.14%

5. R2 SCORE: -0.0140
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.74%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0895 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0809

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   259   6549]
        Up    [   407   7825]

   Precision (when predict Up): 54.44%
   Recall (catch actual Ups): 95.06%

5. R2 SCORE: -0.0139
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.72%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0894 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0794

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   243   6565]
        Up    [   394   7838]

   Precision (when predict Up): 54.42%
   Recall (catch actual Ups): 95.21%

5. R2 SCORE: -0.0140
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.24%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0919 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0804

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   227   6581]
        Up    [   300   7932]

   Precision (when predict Up): 54.65%
   Recall (catch actual Ups): 96.36%

5. R2 SCORE: -0.0133
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.17%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0919 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0810

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   210   6598]
        Up    [   294   7938]

   Precision (when predict Up): 54.61%
   Recall (catch actual Ups): 96.43%

5. R2 SCORE: -0.0130
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.16%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0911 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0825

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   203   6605]
        Up    [   288   7944]

   Precision (when predict Up): 54.60%
   Recall (catch actual Ups): 96.50%

5. R2 SCORE: -0.0126
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.20%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1004 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0829

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   956   5852]
        Up    [  1183   7049]

   Precision (when predict Up): 54.64%
   Recall (catch actual Ups): 85.63%

5. R2 SCORE: -0.0281
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.40%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1011 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0829

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   975   5833]
        Up    [  1171   7061]

   Precision (when predict Up): 54.76%
   Recall (catch actual Ups): 85.78%

5. R2 SCORE: -0.0273
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.26%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0948 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0797

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   970   5838]
        Up    [  1188   7044]

   Precision (when predict Up): 54.68%
   Recall (catch actual Ups): 85.57%

5. R2 SCORE: -0.0279
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.78%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1119 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0911

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   901   5907]
        Up    [  1041   7191]

   Precision (when predict Up): 54.90%
   Recall (catch actual Ups): 87.35%

5. R2 SCORE: -0.0224
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.64%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1095 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0896

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   894   5914]
        Up    [  1056   7176]

   Precision (when predict Up): 54.82%
   Recall (catch actual Ups): 87.17%

5. R2 SCORE: -0.0228
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.58%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1065 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0855

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   821   5987]
        Up    [   993   7239]

   Precision (when predict Up): 54.73%
   Recall (catch actual Ups): 87.94%

5. R2 SCORE: -0.0238
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.85%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1000 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0835

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   391   6417]
        Up    [   521   7711]

   Precision (when predict Up): 54.58%
   Recall (catch actual Ups): 93.67%

5. R2 SCORE: -0.0148
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.81%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0999 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0835

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   372   6436]
        Up    [   508   7724]

   Precision (when predict Up): 54.55%
   Recall (catch actual Ups): 93.83%

5. R2 SCORE: -0.0147
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.56%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0925 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0769

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   341   6467]
        Up    [   515   7717]

   Precision (when predict Up): 54.41%
   Recall (catch actual Ups): 93.74%

5. R2 SCORE: -0.0158
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.96%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0980 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0823

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   273   6535]
        Up    [   388   7844]

   Precision (when predict Up): 54.55%
   Recall (catch actual Ups): 95.29%

5. R2 SCORE: -0.0136
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 54.06%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0989 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0830

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   271   6537]
        Up    [   370   7862]

   Precision (when predict Up): 54.60%
   Recall (catch actual Ups): 95.51%

5. R2 SCORE: -0.0134
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.96%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0961 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0821

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [   255   6553]
        Up    [   369   7863]

   Precision (when predict Up): 54.54%
   Recall (catch actual Ups): 95.52%

5. R2 SCORE: -0.0135
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.12%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1009 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0813

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1163   5645]
        Up    [  1401   6831]

   Precision (when predict Up): 54.75%
   Recall (catch actual Ups): 82.98%

5. R2 SCORE: -0.0315
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 52.79%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.0976 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0801

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1101   5707]
        Up    [  1390   6842]

   Precision (when predict Up): 54.52%
   Recall (catch actual Ups): 83.11%

5. R2 SCORE: -0.0318
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.34%
    Good - better than random

2. INFORMATION COEFFICIENT: 0.1039 (p=0.0000)
    Good - usable signal

3. PEARSON CORRELATION: 0.0848

4. CONFUSION MATRIX:
                 Predicted
                 Down    Up
Actual  Down  [  1148   5660]
        Up    [  1354   6878]

   Precision (when predict Up): 54.86%
   Recall (catch actual Ups): 83.55%

5. R2 SCORE: -0.0291
============================================================
PREDICTION EVALUATION
============================================================
Total observations: 15,040
Dates: 32, Stocks: 470

1. DIRECTIONAL ACCURACY: 53.48%
    Good - better than random


In [ ]:
from itertools import product
import random
random.seed(4212)

with open('src/data_monthly_var/volatility_21_targets.pkl', 'rb') as f:
    monthly_volatility_targets = pickle.load(f)

mask = (monthly_volatility_targets.index >= '2014-03-03') & (monthly_volatility_targets.index <= '2016-10-03')
testing_data = monthly_volatility_targets.loc[mask]
testing_dates = testing_data.index.strftime('%Y-%m-%d').map(lambda x: x+".pkl").values

results_df = {}

for method in ['Ridge', 'Lasso', 'ENet', 'RF', 'XGB']:
    model_params = []
    if method == 'Ridge':
        alphas = [1e-08, 1e-09, 1e-10, 1e-11, 1e-12] # 5 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'Lasso':
        alphas = [.001, .0001, 1e-05, 1e-06] # 4 models
        model_params = [{'alpha': a} for a in alphas]
    elif method == 'ENet':
        alphas = [.001, .0001, 1e-05, 1e-06]
        l1_ratios = [.3, .5, .7]
        model_params = [{'alpha': a, 'l1_ratio': r} for a, r in product(alphas, l1_ratios)] #20 models
    elif method == 'RF':
        n_estimators=[10, 100, 500]
        max_depth=[3, 5, 7]
        min_samples_leaf=[50, 100, 500]
        max_features=['sqrt']
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'min_samples_leaf': l, 'max_features': f, 'n_jobs': j}
                        for n, d, l, f, j in product(n_estimators, max_depth, min_samples_leaf, max_features, [n_jobs])] #24 models
    elif method == 'XGB':
        n_estimators=[10, 100, 200]
        max_depth=[3, 5, 7]
        learning_rate=[0.05, 0.1]
        min_child_weight=[100, 200]
        reg_lambda=[.1, 1, 5]
        subsample=[0.8]
        colsample_bytree=[0.8]
        n_jobs=-1
        model_params = [{'n_estimators': n, 'max_depth': d, 'learning_rate': lr,
                         'min_child_weight': mcw, 'reg_lambda': rl,
                         'subsample': ss, 'colsample_bytree': cb,
                         'n_jobs': j}
                        for n, d, lr, mcw, rl, ss, cb, j in
                        product(n_estimators, max_depth, learning_rate,
                                min_child_weight, reg_lambda,
                                subsample, colsample_bytree, [n_jobs])]
    def model_cv(model_params) -> dict:
        preds = []

        for test_date in testing_dates:
            predictor = MLReturnPredictor(model_type=method, **model_params)
            v = os.listdir('src/data_monthly_var')[:os.listdir('src/data_monthly_var').index(test_date)-4]
            X_train, y_train = predictor.create_training_dataset(v, "monthly_var", monthly_volatility_targets)
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            predictor.train(X_train, np.log(y_train))
            predicted = np.exp(predictor.predict_all_test_returns([test_date], "monthly_var", scaler))
            preds.append(predicted)

        predicted = pd.concat(preds)
        return predicted

    weights_list = Parallel(n_jobs=-1)(
        delayed(model_cv)(d) for d in tqdm(model_params)
    )

    for i in range(len(weights_list)):
        model_param = model_params[i]
        results = evaluate_predictions(weights_list[i], testing_data, for_returns=False)
        results_df[(method, frozenset(model_param.items()))] = results
results_df = pd.DataFrame(results_df).T
results_df.to_pickle('src/cv_results/monthly_volatility_model_results.pkl')

100%|██████████| 6/6 [00:00<00:00, 9982.48it/s]

5. R2 SCORE: -0.1222
   RMSE: 0.2104

5. R2 SCORE: -0.1222
   RMSE: 0.2104

5. R2 SCORE: -0.1219
   RMSE: 0.2104

5. R2 SCORE: -0.1195
   RMSE: 0.2102

5. R2 SCORE: -0.1061
   RMSE: 0.2089

5. R2 SCORE: -0.0932
   RMSE: 0.2077

100%|██████████| 6/6 [00:00<00:00, 5873.00it/s]

5. R2 SCORE: -0.7274
   RMSE: 0.2611

5. R2 SCORE: -0.1489
   RMSE: 0.2129

5. R2 SCORE: -0.1159
   RMSE: 0.2098

5. R2 SCORE: -0.1214
   RMSE: 0.2103

5. R2 SCORE: -0.1221
   RMSE: 0.2104

5. R2 SCORE: -0.1222
   RMSE: 0.2104

100%|██████████| 15/15 [00:00<00:00, 13611.98it/s]

5. R2 SCORE: -0.1080
   RMSE: 0.2091

5. R2 SCORE: -0.4494
   RMSE: 0.2391

5. R2 SCORE: -0.8350
   RMSE: 0.2691

5. R2 SCORE: -0.7785
   RMSE: 0.2649

5. R2 SCORE: -0.7540
   RMSE: 0.2631

5. R2 SCORE: -0.1051
   RMSE: 0.2088

5. R2 SCORE: -0.1182
   RMSE: 0.2100

5. R2 SCORE: -0.1267
   RMSE: 0.2108

5. R2 SCORE: -0.1337
   RMSE: 0.2115

5. R2 SCORE: -0.1437
   RMSE: 0.2124

5. R2 SCORE: -0.1196
   RMSE: 0.2102

5. R2 SCORE: -0.1181
   RMSE: 0.2100

5. R2 SCORE: -0.1170
   RMSE: 0.2099

5. R2 SCORE: -0.1162
   RMSE: 0.2099

5. R2 SCORE: -0.1158
   RMSE: 0.2098

100%|██████████| 27/27 [00:00<00:00, 26453.21it/s]

5. R2 SCORE: 0.0198
   RMSE: 0.1967

5. R2 SCORE: 0.0195
   RMSE: 0.1967

5. R2 SCORE: 0.0126
   RMSE: 0.1974

5. R2 SCORE: 0.0344
   RMSE: 0.1952

5. R2 SCORE: 0.0301
   RMSE: 0.1956

5. R2 SCORE: 0.0132
   RMSE: 0.1973

5. R2 SCORE: 0.0386
   RMSE: 0.1948

5. R2 SCORE: 0.0299
   RMSE: 0.1956

5. R2 SCORE: 0.0127
   RMSE: 0.1974

5. R2 SCORE: 0.0192
   RMSE: 0.1967

5. R2 SCORE: 0.0190
   RMSE: 0.1967

5. R2 SCORE: 0.0125
   RMSE: 0.1974

5. R2 SCORE: 0.0336
   RMSE: 0.1953

5. R2 SCORE: 0.0300
   RMSE: 0.1956

5. R2 SCORE: 0.0137
   RMSE: 0.1973

5. R2 SCORE: 0.0378
   RMSE: 0.1948

5. R2 SCORE: 0.0317
   RMSE: 0.1955

5. R2 SCORE: 0.0134
   RMSE: 0.1973

5. R2 SCORE: 0.0195
   RMSE: 0.1967

5. R2 SCORE: 0.0192
   RMSE: 0.1967

5. R2 SCORE: 0.0125
   RMSE: 0.1974

5. R2 SCORE: 0.0334
   RMSE: 0.1953

5. R2 SCORE: 0.0303
   RMSE: 0.1956

5. R2 SCORE: 0.0135
   RMSE: 0.1973

5. R2 SCORE: 0.0375
   RMSE: 0.1949

5. R2 SCORE: 0.0316
   RMSE: 0.1955

5. R2 SCORE: 0.0135
   RMSE: 0.1973

100%|██████████| 108/108 [01:41<00:00,  1.06it/s]

5. R2 SCORE: -0.0096
   RMSE: 0.1996

5. R2 SCORE: -0.0097
   RMSE: 0.1996

5. R2 SCORE: -0.0100
   RMSE: 0.1996

5. R2 SCORE: -0.0098
   RMSE: 0.1996

5. R2 SCORE: -0.0099
   RMSE: 0.1996

5. R2 SCORE: -0.0101
   RMSE: 0.1996

5. R2 SCORE: 0.0066
   RMSE: 0.1980

5. R2 SCORE: 0.0064
   RMSE: 0.1980

5. R2 SCORE: 0.0060
   RMSE: 0.1980

5. R2 SCORE: 0.0060
   RMSE: 0.1980

5. R2 SCORE: 0.0058
   RMSE: 0.1981

5. R2 SCORE: 0.0055
   RMSE: 0.1981

5. R2 SCORE: -0.0069
   RMSE: 0.1993

5. R2 SCORE: -0.0071
   RMSE: 0.1993

5. R2 SCORE: -0.0079
   RMSE: 0.1994

5. R2 SCORE: -0.0082
   RMSE: 0.1995

5. R2 SCORE: -0.0084
   RMSE: 0.1995

5. R2 SCORE: -0.0085
   RMSE: 0.1995

5. R2 SCORE: 0.0117
   RMSE: 0.1975

5. R2 SCORE: 0.0117
   RMSE: 0.1975

5. R2 SCORE: 0.0102
   RMSE: 0.1976

5. R2 SCORE: 0.0092
   RMSE: 0.1977

5. R2 SCORE: 0.0092
   RMSE: 0.1977

5. R2 SCORE: 0.0086
   RMSE: 0.1978

5. R2 SCORE: -0.0066
   RMSE: 0.1993

5. R2 SCORE: -0.0068
   RMSE: 0.1993

5. R2 SCORE: -0.0076
   RMSE: 0.1994

5. R2 SCORE: -0.0083
   RMSE: 0.1995

5. R2 SCORE: -0.0083
   RMSE: 0.1995

5. R2 SCORE: -0.0085
   RMSE: 0.1995

5. R2 SCORE: 0.0123
   RMSE: 0.1974

5. R2 SCORE: 0.0121
   RMSE: 0.1974

5. R2 SCORE: 0.0107
   RMSE: 0.1976

5. R2 SCORE: 0.0090
   RMSE: 0.1977

5. R2 SCORE: 0.0089
   RMSE: 0.1977

5. R2 SCORE: 0.0085
   RMSE: 0.1978

5. R2 SCORE: 0.0427
   RMSE: 0.1944

5. R2 SCORE: 0.0419
   RMSE: 0.1944

5. R2 SCORE: 0.0415
   RMSE: 0.1945

5. R2 SCORE: 0.0389
   RMSE: 0.1947

5. R2 SCORE: 0.0388
   RMSE: 0.1947

5. R2 SCORE: 0.0386
   RMSE: 0.1948

5. R2 SCORE: 0.0482
   RMSE: 0.1938

5. R2 SCORE: 0.0498
   RMSE: 0.1936

5. R2 SCORE: 0.0489
   RMSE: 0.1937

5. R2 SCORE: 0.0442
   RMSE: 0.1942

5. R2 SCORE: 0.0444
   RMSE: 0.1942

5. R2 SCORE: 0.0443
   RMSE: 0.1942

5. R2 SCORE: 0.0471
   RMSE: 0.1939

5. R2 SCORE: 0.0471
   RMSE: 0.1939

5. R2 SCORE: 0.0462
   RMSE: 0.1940

5. R2 SCORE: 0.0420
   RMSE: 0.1944

5. R2 SCORE: 0.0421
   RMSE: 0.1944

5. R2 SCORE: 0.0418
   RMSE: 0.1944

5. R2 SCORE: 0.0527
   RMSE: 0.1933

5. R2 SCORE: 0.0515
   RMSE: 0.1935

5. R2 SCORE: 0.0511
   RMSE: 0.1935

5. R2 SCORE: 0.0461
   RMSE: 0.1940

5. R2 SCORE: 0.0465
   RMSE: 0.1940

5. R2 SCORE: 0.0464
   RMSE: 0.1940

5. R2 SCORE: 0.0482
   RMSE: 0.1938

5. R2 SCORE: 0.0484
   RMSE: 0.1938

5. R2 SCORE: 0.0475
   RMSE: 0.1939

5. R2 SCORE: 0.0426
   RMSE: 0.1944

5. R2 SCORE: 0.0424
   RMSE: 0.1944

5. R2 SCORE: 0.0422
   RMSE: 0.1944

5. R2 SCORE: 0.0524
   RMSE: 0.1934

5. R2 SCORE: 0.0522
   RMSE: 0.1934

5. R2 SCORE: 0.0516
   RMSE: 0.1934

5. R2 SCORE: 0.0465
   RMSE: 0.1940

5. R2 SCORE: 0.0472
   RMSE: 0.1939

5. R2 SCORE: 0.0462
   RMSE: 0.1940

5. R2 SCORE: 0.0493
   RMSE: 0.1937

5. R2 SCORE: 0.0490
   RMSE: 0.1937

5. R2 SCORE: 0.0484
   RMSE: 0.1938

5. R2 SCORE: 0.0449
   RMSE: 0.1941

5. R2 SCORE: 0.0446
   RMSE: 0.1942

5. R2 SCORE: 0.0446
   RMSE: 0.1942

5. R2 SCORE: 0.0524
   RMSE: 0.1934

5. R2 SCORE: 0.0546
   RMSE: 0.1931

5. R2 SCORE: 0.0526
   RMSE: 0.1933

5. R2 SCORE: 0.0470
   RMSE: 0.1939

5. R2 SCORE: 0.0474
   RMSE: 0.1939

5. R2 SCORE: 0.0479
   RMSE: 0.1938

5. R2 SCORE: 0.0522
   RMSE: 0.1934

5. R2 SCORE: 0.0516
   RMSE: 0.1934

5. R2 SCORE: 0.0513
   RMSE: 0.1935

5. R2 SCORE: 0.0465
   RMSE: 0.1940

5. R2 SCORE: 0.0465
   RMSE: 0.1940

5. R2 SCORE: 0.0464
   RMSE: 0.1940

5. R2 SCORE: 0.0540
   RMSE: 0.1932

5. R2 SCORE: 0.0529
   RMSE: 0.1933

5. R2 SCORE: 0.0532
   RMSE: 0.1933

5. R2 SCORE: 0.0484
   RMSE: 0.1938

5. R2 SCORE: 0.0490
   RMSE: 0.1937

5. R2 SCORE: 0.0494
   RMSE: 0.1937

5. R2 SCORE: 0.0525
   RMSE: 0.1934

5. R2 SCORE: 0.0523
   RMSE: 0.1934

5. R2 SCORE: 0.0524
   RMSE: 0.1934

5. R2 SCORE: 0.0467
   RMSE: 0.1939

5. R2 SCORE: 0.0466
   RMSE: 0.1939

5. R2 SCORE: 0.0468
   RMSE: 0.1939

5. R2 SCORE: 0.0532
   RMSE: 0.1933

5. R2 SCORE: 0.0530
   RMSE: 0.1933

5. R2 SCORE: 0.0526
   RMSE: 0.1933

5. R2 SCORE: 0.0487
   RMSE: 0.1937

5. R2 SCORE: 0.0495
   RMSE: 0.1937

5. R2 SCORE: 0.0483
   RMSE: 0.1938

In [24]:
results_df.iloc[12:30]

                                                         r2_score      rmse
ENet ((l1_ratio, 0.1), (alpha, 0.01))                   -0.108037  0.209092
     ((alpha, 0.01), (l1_ratio, 0.3))                   -0.449377  0.239139
     ((alpha, 0.01), (l1_ratio, 0.5))                   -0.834976  0.269076
     ((l1_ratio, 0.7), (alpha, 0.01))                   -0.778451  0.264900
     ((l1_ratio, 0.9), (alpha, 0.01))                   -0.754014  0.263073
     ((l1_ratio, 0.1), (alpha, 0.001))                  -0.105127  0.208817
     ((l1_ratio, 0.3), (alpha, 0.001))                  -0.118150  0.210044
     ((l1_ratio, 0.5), (alpha, 0.001))                  -0.126698  0.210845
     ((l1_ratio, 0.7), (alpha, 0.001))                  -0.133663  0.211496
     ((l1_ratio, 0.9), (alpha, 0.001))                  -0.143680  0.212428
     ((l1_ratio, 0.1), (alpha, 0.0001))                 -0.119619  0.210182
     ((alpha, 0.0001), (l1_ratio, 0.3))                 -0.118146  0.210044
     ((l1_ratio, 0.5), (alpha, 0.0001))                 -0.117001  0.209936
     ((l1_ratio, 0.7), (alpha, 0.0001))                 -0.116190  0.209860
     ((l1_ratio, 0.9), (alpha, 0.0001))                 -0.115841  0.209827
RF   ((n_estimators, 10), (max_depth, 3), (min_sampl...  0.019813  0.196659
     ((n_estimators, 10), (min_samples_leaf, 100), (...  0.019472  0.196694
     ((n_estimators, 10), (max_depth, 3), (min_sampl...  0.012615  0.197380

In [ ]:
def evaluate_predictions(predicted_df, actual_df, for_returns=True) -> dict:
    """
    Evaluate prediction quality for returns
    
    Args:
        predicted_df: DataFrame (dates × stocks) with predicted returns
        actual_df: DataFrame (dates × stocks) with actual returns
    """
    
    # Align dataframes
    common_dates = predicted_df.index.intersection(actual_df.index)
    common_stocks = predicted_df.columns.intersection(actual_df.columns)
    
    pred = predicted_df.loc[common_dates, common_stocks]
    actual = actual_df.loc[common_dates, common_stocks]
    
    # Flatten to 1D arrays (drop NaNs)
    pred_flat = pred.values.flatten()
    actual_flat = actual.values.flatten()
    
    valid_mask = ~(np.isnan(pred_flat) | np.isnan(actual_flat))
    pred_flat = pred_flat[valid_mask]
    actual_flat = actual_flat[valid_mask]

    if not for_returns:
        r2 = r2_score(actual_flat, pred_flat)
        print(f"\n5. R2 SCORE: {r2:.4f}")

        rmse = np.sqrt(np.mean((pred_flat - actual_flat) ** 2))
        print(f"   RMSE: {rmse:.4f}")

        mae = np.mean(np.abs(pred_flat - actual_flat))
        print(f"   MAE: {mae:.4f}")

        return {'r2_score': r2,
                'rmse': rmse,
                'mae': mae}   
    
    print("="*60)
    print("PREDICTION EVALUATION")
    print("="*60)
    print(f"Total observations: {len(pred_flat):,}")
    print(f"Dates: {len(common_dates)}, Stocks: {len(common_stocks)}")
    
    # 1. Directional Accuracy
    direction_correct = (np.sign(pred_flat) == np.sign(actual_flat)).mean()
    print(f"\n1. DIRECTIONAL ACCURACY: {direction_correct:.2%}")
    
    if direction_correct > 0.52:
        print("    Good - better than random")
    elif direction_correct > 0.50:
        print("   ~ Weak signal")
    else:
        print("   ✗ Worse than random!")
    
    # 2. Information Coefficient (Spearman)
    ic, ic_pval = spearmanr(pred_flat, actual_flat)
    print(f"\n2. INFORMATION COEFFICIENT: {ic:.4f} (p={ic_pval:.4f})")
    
    if ic > 0.05:
        print("    Good - usable signal")
    elif ic > 0.02:
        print("   ~ Weak but non-zero")
    else:
        print("   ✗ Very weak signal")
    
    # 3. Pearson Correlation (for comparison)
    pearson_corr = np.corrcoef(pred_flat, actual_flat)[0, 1]
    print(f"\n3. PEARSON CORRELATION: {pearson_corr:.4f}")
    
    # 4. Confusion Matrix
    pred_sign = np.sign(pred_flat)
    actual_sign = np.sign(actual_flat)
    
    # Map to Up/Down (ignore zeros for clarity)
    pred_binary = (pred_sign > 0).astype(int)
    actual_binary = (actual_sign > 0).astype(int)
    
    cm = confusion_matrix(actual_binary, pred_binary)
    
    print(f"\n4. CONFUSION MATRIX:")
    print(f"                 Predicted")
    print(f"                 Down    Up")
    print(f"Actual  Down  [{cm[0,0]:6d} {cm[0,1]:6d}]")
    print(f"        Up    [{cm[1,0]:6d} {cm[1,1]:6d}]")
    
    # Precision and Recall
    precision = cm[1,1] / (cm[1,1] + cm[0,1]) if (cm[1,1] + cm[0,1]) > 0 else 0
    recall = cm[1,1] / (cm[1,1] + cm[1,0]) if (cm[1,1] + cm[1,0]) > 0 else 0
    
    print(f"\n   Precision (when predict Up): {precision:.2%}")
    print(f"   Recall (catch actual Ups): {recall:.2%}")

    # 5. R2 Score
    r2 = r2_score(actual_flat, pred_flat)
    print(f"\n5. R2 SCORE: {r2:.4f}")
    
    return {
        'directional_accuracy': direction_correct,
        'information_coefficient': ic,
        'pearson_correlation': pearson_corr,
        'confusion_matrix': cm,
        'precision': precision,
        'recall': recall,
        'r2_score': r2
    }

In [13]:
p = {}

for date in testing_data.index:
    working = returns.loc[:date].iloc[:-1]
    working = working.mean()
    p[date] = working
p = pd.DataFrame(p).T
p.index = testing_data.index
p.set_index(testing_data.index, inplace=True)
evaluate_predictions(p, testing_data)

NameError: name 'returns' is not defined

In [ ]:
features = []
for i in range(X_train.T.shape[0]):
    features.append(np.corrcoef(X_train.T[i], y_train)[0, 1])

with open('src/data_weekly_ret/2013-06-10.pkl', 'rb') as f:
    f = pickle.load(f)

feature_importances = pd.Series(features, index=[f'Feature_{i}' for i in range(X_train.T.shape[0])])
feature_importances.index = f.columns
feature_importances = feature_importances.abs().sort_values(ascending=False)
print("Top 10 important features:")
print(feature_importances.head(10))
feature_importances

Purge period either 70 trading days, 14 trasing weeks, 4 trading months

In [ ]:
# testing_dates = test_returns.index.strftime('%Y-%m-%d').map(lambda x: x+".pkl").values

with open('src/data_weekly_var/weekly_volatility_targets.pkl', 'rb') as f:
    weekly_volatility_targets = pickle.load(f)

test_weekly_var = weekly_volatility_targets.loc['2017-02-08':]

testing_dates = test_weekly_var.index.strftime('%Y-%m-%d').map(lambda x: x+".pkl").values

preds = []

for test_date in testing_dates:
    predictor = MLReturnPredictor(model_type='ridge', alpha=.1)
    X_train, y_train = predictor.create_training_dataset(os.listdir('src/data_weekly_var')[:os.listdir('src/data_weekly_var').index(test_date)-10],
                                                        np.log(weekly_volatility_targets)) #65 for purge
    predictor.train(X_train, y_train)
    predicted = predictor.predict_all_test_returns([test_date])
    preds.append(predicted)

predicted = pd.concat(preds)
predicted = np.exp(predicted)

Generate weights for variance

In [ ]:
tickers = predicted.columns.tolist()

def compute_weights_for_date(date):
    opt = PortfolioOptimizer(returns.loc[:date].iloc[:-1]).minimum_variance_from_cov(predicted.loc[[date]], max_position=0.05)
    return pd.Series(opt, index=tickers)

weights_list = Parallel(n_jobs=-1)(
    delayed(compute_weights_for_date)(d) for d in tqdm(predicted.index, desc="weights")
)

weights = pd.concat(weights_list, axis=1).T
weights.index.name = 'date'
weights.index = predicted.index

with open('weights_variance.pkl', 'wb') as f:
    pickle.dump(weights, f)

The one below takes very long btw

Chooses optimal portfolio based on predicted returns

In [ ]:
tickers = predicted.columns.tolist()

def compute_weights_for_date(date):
    predicted_returns = pd.concat([returns.loc[:date].iloc[:-1], predicted.loc[[date]]])
    opt = PortfolioOptimizer(predicted_returns).minimum_variance(max_position=0.05)
    return pd.Series(opt, index=tickers)

weights_list = Parallel(n_jobs=-1)(
    delayed(compute_weights_for_date)(d) for d in tqdm(predicted.index[:5], desc="weights")
)

weights = pd.concat(weights_list, axis=1).T
weights.index.name = 'date'
weights.index = predicted.index[:5]

with open('weights.pkl', 'wb') as f:
    pickle.dump(weights, f)

In [ ]:
returns.head(5).sum(axis=0)

In [ ]:
date_idx = returns.index.get_loc("2018-02-07")
window_start = date_idx - 70
window_end = date_idx
returns_window = returns.iloc[window_start:window_end]
returns_window

In [ ]:
spy_weights = volume.shift(1)
close_prices = close.shift(1)
spy_weights = spy_weights.loc["2017-02-08":"2018-02-07"]
close_prices = close_prices.loc["2017-02-08":"2018-02-07"]
spy_weights = spy_weights*close_prices
spy_weights = spy_weights.div(spy_weights.sum(axis=1), axis=0)
spy_weights.head()

Preparing backtest

In [ ]:
backtester = WalkForwardBacktest(
    train_returns=train_returns,
    test_returns=test_returns,
    # test_prices=test_prices,
    rf_rate_test=test_risk_free_rate,
    rebalance_freq='D'  # Weekly
)

running backtest

In [ ]:
results = {}

with open('weights.pkl', 'rb') as f:
    weights = pickle.load(f)

# Run Equal Weight
results['ML w fees'] = backtester.run_backtest_preloaded_weights(
    strategy_name='ML',
    preloaded_weights=weights,
    transaction_cost_bps=10
)

results['ML no fees'] = backtester.run_backtest_preloaded_weights(
    strategy_name='ML',
    preloaded_weights=weights,
    transaction_cost_bps=0
)


weights = weights.iloc[[0]]

for col in weights.columns:
    weights[col].values[:] = 1/470

results['Base - Buy & Hold'] = backtester.run_backtest_preloaded_weights(
    strategy_name='ML',
    preloaded_weights=weights,
    transaction_cost_bps=0
)

with open('weights_variance.pkl', 'rb') as f:
    weights_var = pickle.load(f)

results['vol'] = backtester.run_backtest_preloaded_weights(
    strategy_name='Volatility',
    preloaded_weights=weights_var,
    transaction_cost_bps=0
)

Evaluation

In [ ]:
results['vol']

In [ ]:
evaluator = PerformanceEvaluator(test_risk_free_rate)

comparison_df = evaluator.compare_strategies(results)
print("\nPerformance Comparison:")
print(comparison_df.to_string())

# ============================================================
# STEP 5: Visualize Results
# ============================================================
print("\n5. Generating Visualizations")
print("-" * 60)

fig = evaluator.plot_results(results, figsize=(15, 10))
plt.show()

fred = Fred(api_key = os.getenv("API_KEY"))
spy = fred.get_series_latest_release('SP500').loc["2017-02-08":"2018-02-07"]
spy.plot()
plt.show()